trigger:
- master

variables:
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'
  webappname: 'LoggingAPI'
  subscription: ''
  outputDirectory: '$(Build.ArtifactStagingDirectory)'
  buildArtifactName: 'drop'

stages:
- stage: Build
  displayName: Build Stage (CI)
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
       
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore .NET Core project files'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build .NET Core project files'
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish .NET Core project files'
      inputs:
        command: 'publish'
        publishWebProjects: False
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(outputDirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        pathtoPublish: '$(outputDirectory)'
        artifactName: '$(buildArtifactName)'

